"""
Dados de entrada (mini mundo).

Este arquivo deve ser fácil de editar e entender: apenas constantes.
"""

# Demandas por dia (0-24 continua existindo no modelo, mas usamos faixa 06–22 nas demandas).
DEMANDS_BY_DAY = {
    1: [
        {"id": "A", "start": 6, "end": 9, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 10, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 7, "is_pediatric": False},
        {"id": "G", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "C", "start": 7, "end": 12, "is_pediatric": True},
        {"id": "H", "start": 7, "end": 10, "is_pediatric": False},
        {"id": "D", "start": 8, "end": 11, "is_pediatric": False},
        {"id": "E", "start": 8, "end": 12, "is_pediatric": False},
        {"id": "C", "start": 9, "end": 10, "is_pediatric": False},
        {"id": "E", "start": 9, "end": 13, "is_pediatric": False},
        {"id": "F", "start": 10, "end": 14, "is_pediatric": False},
        {"id": "G", "start": 11, "end": 15, "is_pediatric": False},
        {"id": "H", "start": 12, "end": 16, "is_pediatric": False},
        {"id": "A", "start": 13, "end": 17, "is_pediatric": True},
        {"id": "B", "start": 14, "end": 18, "is_pediatric": False},
        {"id": "C", "start": 15, "end": 19, "is_pediatric": False},
        {"id": "D", "start": 16, "end": 20, "is_pediatric": False},
        {"id": "D", "start": 17, "end": 19, "is_pediatric": False},
        {"id": "E", "start": 18, "end": 22, "is_pediatric": False},
        {"id": "G", "start": 18, "end": 21, "is_pediatric": False},
        {"id": "H", "start": 20, "end": 22, "is_pediatric": False},
        {"id": "E", "start": 21, "end": 22, "is_pediatric": False},
        {"id": "F", "start": 19, "end": 22, "is_pediatric": True},
        # Extra: +9 demandas (mais variação de início/fim; ~2–4h)
        {"id": "A", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "B", "start": 7, "end": 11, "is_pediatric": False},
        {"id": "C", "start": 9, "end": 12, "is_pediatric": False},
        {"id": "D", "start": 10, "end": 14, "is_pediatric": False},
        {"id": "E", "start": 12, "end": 15, "is_pediatric": False},
        {"id": "F", "start": 13, "end": 16, "is_pediatric": False},
        {"id": "G", "start": 15, "end": 18, "is_pediatric": False},
        {"id": "H", "start": 17, "end": 20, "is_pediatric": False},
        {"id": "A", "start": 19, "end": 22, "is_pediatric": False},
    ],
    2: [
        {"id": "A", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 11, "is_pediatric": False},
        {"id": "A", "start": 6, "end": 7, "is_pediatric": False},
        {"id": "D", "start": 6, "end": 9, "is_pediatric": False},
        {"id": "E", "start": 7, "end": 9, "is_pediatric": False},
        {"id": "C", "start": 7, "end": 10, "is_pediatric": True},
        {"id": "D", "start": 8, "end": 12, "is_pediatric": False},
        {"id": "G", "start": 8, "end": 11, "is_pediatric": False},
        {"id": "H", "start": 9, "end": 12, "is_pediatric": False},
        {"id": "E", "start": 9, "end": 13, "is_pediatric": False},
        {"id": "F", "start": 10, "end": 14, "is_pediatric": True},
        {"id": "G", "start": 11, "end": 15, "is_pediatric": False},
        {"id": "H", "start": 12, "end": 16, "is_pediatric": False},
        {"id": "A", "start": 13, "end": 17, "is_pediatric": False},
        {"id": "B", "start": 14, "end": 18, "is_pediatric": True},
        {"id": "C", "start": 15, "end": 19, "is_pediatric": False},
        {"id": "D", "start": 16, "end": 20, "is_pediatric": False},
        {"id": "G", "start": 17, "end": 19, "is_pediatric": False},
        {"id": "E", "start": 18, "end": 22, "is_pediatric": False},
        {"id": "H", "start": 18, "end": 21, "is_pediatric": False},
        {"id": "A", "start": 20, "end": 22, "is_pediatric": False},
        {"id": "D", "start": 19, "end": 22, "is_pediatric": False},
        # Extra: +9 demandas (mais variação de início/fim; ~2–4h)
        {"id": "A", "start": 6, "end": 9, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "C", "start": 8, "end": 11, "is_pediatric": False},
        {"id": "D", "start": 9, "end": 13, "is_pediatric": False},
        {"id": "E", "start": 11, "end": 14, "is_pediatric": False},
        {"id": "F", "start": 12, "end": 16, "is_pediatric": False},
        {"id": "G", "start": 14, "end": 17, "is_pediatric": False},
        {"id": "H", "start": 16, "end": 18, "is_pediatric": False},
        {"id": "A", "start": 20, "end": 22, "is_pediatric": False},
    ],
    3: [
        {"id": "A", "start": 6, "end": 10, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 9, "is_pediatric": False},
        {"id": "E", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "C", "start": 7, "end": 11, "is_pediatric": True},
        {"id": "D", "start": 8, "end": 12, "is_pediatric": False},
        {"id": "H", "start": 8, "end": 11, "is_pediatric": False},
        {"id": "F", "start": 7, "end": 9, "is_pediatric": False},
        {"id": "E", "start": 9, "end": 14, "is_pediatric": False},
        {"id": "F", "start": 10, "end": 13, "is_pediatric": False},
        {"id": "G", "start": 11, "end": 15, "is_pediatric": True},
        {"id": "H", "start": 12, "end": 16, "is_pediatric": False},
        {"id": "A", "start": 13, "end": 17, "is_pediatric": False},
        {"id": "B", "start": 14, "end": 18, "is_pediatric": False},
        {"id": "C", "start": 15, "end": 19, "is_pediatric": False},
        {"id": "D", "start": 16, "end": 20, "is_pediatric": True},
        {"id": "A", "start": 17, "end": 19, "is_pediatric": False},
        {"id": "E", "start": 18, "end": 22, "is_pediatric": False},
        {"id": "F", "start": 18, "end": 21, "is_pediatric": False},
        {"id": "G", "start": 20, "end": 22, "is_pediatric": False},
        {"id": "H", "start": 19, "end": 22, "is_pediatric": False},
        # Extra: +9 demandas (mais variação de início/fim; ~2–4h)
        {"id": "A", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "B", "start": 7, "end": 9, "is_pediatric": False},
        {"id": "C", "start": 8, "end": 12, "is_pediatric": False},
        {"id": "D", "start": 9, "end": 11, "is_pediatric": False},
        {"id": "E", "start": 10, "end": 13, "is_pediatric": False},
        {"id": "F", "start": 12, "end": 15, "is_pediatric": False},
        {"id": "G", "start": 14, "end": 18, "is_pediatric": False},
        {"id": "H", "start": 17, "end": 19, "is_pediatric": False},
        {"id": "A", "start": 19, "end": 22, "is_pediatric": False},
    ],
    4: [
        {"id": "A", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 10, "is_pediatric": False},
        {"id": "E", "start": 6, "end": 9, "is_pediatric": False},
        {"id": "A", "start": 6, "end": 7, "is_pediatric": False},
        {"id": "C", "start": 7, "end": 12, "is_pediatric": True},
        {"id": "B", "start": 7, "end": 9, "is_pediatric": False},
        {"id": "D", "start": 8, "end": 13, "is_pediatric": False},
        {"id": "G", "start": 8, "end": 11, "is_pediatric": False},
        {"id": "E", "start": 9, "end": 11, "is_pediatric": False},
        {"id": "F", "start": 10, "end": 14, "is_pediatric": False},
        {"id": "G", "start": 11, "end": 15, "is_pediatric": False},
        {"id": "H", "start": 12, "end": 16, "is_pediatric": True},
        {"id": "A", "start": 13, "end": 17, "is_pediatric": False},
        {"id": "B", "start": 14, "end": 18, "is_pediatric": False},
        {"id": "C", "start": 15, "end": 19, "is_pediatric": False},
        {"id": "D", "start": 16, "end": 20, "is_pediatric": True},
        {"id": "C", "start": 17, "end": 19, "is_pediatric": False},
        {"id": "E", "start": 18, "end": 22, "is_pediatric": False},
        {"id": "F", "start": 18, "end": 21, "is_pediatric": False},
        {"id": "G", "start": 20, "end": 22, "is_pediatric": False},
        {"id": "D", "start": 19, "end": 22, "is_pediatric": False},
        # Extra: +9 demandas (mais variação de início/fim; ~2–4h)
        {"id": "A", "start": 6, "end": 10, "is_pediatric": False},
        {"id": "B", "start": 7, "end": 9, "is_pediatric": False},
        {"id": "C", "start": 8, "end": 11, "is_pediatric": False},
        {"id": "D", "start": 9, "end": 12, "is_pediatric": False},
        {"id": "E", "start": 10, "end": 12, "is_pediatric": False},
        {"id": "F", "start": 11, "end": 15, "is_pediatric": False},
        {"id": "G", "start": 13, "end": 16, "is_pediatric": False},
        {"id": "H", "start": 16, "end": 20, "is_pediatric": False},
        {"id": "A", "start": 19, "end": 22, "is_pediatric": False},
    ],
    5: [
        {"id": "A", "start": 6, "end": 9, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 10, "is_pediatric": True},
        {"id": "D", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "E", "start": 6, "end": 7, "is_pediatric": False},
        {"id": "C", "start": 7, "end": 11, "is_pediatric": False},
        {"id": "D", "start": 8, "end": 12, "is_pediatric": False},
        {"id": "H", "start": 8, "end": 11, "is_pediatric": False},
        {"id": "F", "start": 7, "end": 9, "is_pediatric": False},
        {"id": "E", "start": 9, "end": 13, "is_pediatric": False},
        {"id": "F", "start": 10, "end": 14, "is_pediatric": False},
        {"id": "G", "start": 11, "end": 15, "is_pediatric": True},
        {"id": "H", "start": 12, "end": 16, "is_pediatric": False},
        {"id": "A", "start": 13, "end": 17, "is_pediatric": False},
        {"id": "B", "start": 14, "end": 18, "is_pediatric": False},
        {"id": "C", "start": 15, "end": 19, "is_pediatric": False},
        {"id": "D", "start": 16, "end": 20, "is_pediatric": True},
        {"id": "A", "start": 17, "end": 19, "is_pediatric": False},
        {"id": "E", "start": 18, "end": 22, "is_pediatric": False},
        {"id": "F", "start": 18, "end": 21, "is_pediatric": False},
        {"id": "G", "start": 20, "end": 22, "is_pediatric": False},
        {"id": "B", "start": 19, "end": 22, "is_pediatric": False},
        # Extra: +9 demandas (mais variação de início/fim; ~2–4h)
        {"id": "A", "start": 6, "end": 8, "is_pediatric": False},
        {"id": "B", "start": 6, "end": 9, "is_pediatric": False},
        {"id": "C", "start": 8, "end": 10, "is_pediatric": False},
        {"id": "D", "start": 9, "end": 12, "is_pediatric": False},
        {"id": "E", "start": 10, "end": 14, "is_pediatric": False},
        {"id": "F", "start": 12, "end": 15, "is_pediatric": False},
        {"id": "G", "start": 13, "end": 17, "is_pediatric": False},
        {"id": "H", "start": 16, "end": 18, "is_pediatric": False},
        {"id": "A", "start": 19, "end": 22, "is_pediatric": False},
    ],
}


PROS = [
    {"id": "Joaquim", "sequence": 1, "can_peds": False, "vacation": [(13, 17)]},
    {"id": "Nicolas", "sequence": 2, "can_peds": False, "vacation": [(7, 12)]},
    {"id": "Carlota", "sequence": 3, "can_peds": False, "vacation": []},
    {"id": "Mariana", "sequence": 4, "can_peds": True, "vacation": []},
    {"id": "Fabiano", "sequence": 5, "can_peds": False, "vacation": []},
    {"id": "Julieta", "sequence": 6, "can_peds": True, "vacation": []},
    {"id": "Gustavo", "sequence": 7, "can_peds": False, "vacation": []},
    {"id": "Ricardo", "sequence": 8, "can_peds": False, "vacation": [(0, 24)]},
    {"id": "Augusto", "sequence": 9, "can_peds": False, "vacation": []},
    {"id": "Camilla", "sequence": 10, "can_peds": False, "vacation": []},
]

