export function LoadingSpinner() {
    return (
        <span className="inline" style={{ verticalAlign: 'baseline' }}>
            <svg
                xmlns="http://www.w3.org/2000/svg"
                className="inline"
                style={{ verticalAlign: 'baseline', display: 'inline-block', margin: 0, padding: 0 }}
                width="10mm"
                height="1mm"
                viewBox="0 0 10 1"
            >
                <rect
                    x="0"
                    y="0"
                    width="10"
                    height="1"
                    fill="white"
                    stroke="gray"
                    strokeWidth="0.5"
                    vectorEffect="non-scaling-stroke"
                    opacity="0.75"
                />
                <rect
                    x="0"
                    y="0"
                    width="1"
                    height="1" fill="gray"
                    opacity="0.75">
                    <animate
                        attributeName="x"
                        values="0;9;0"
                        dur="2s"
                        repeatCount="indefinite"
                        calcMode="linear"
                    />
                </rect>
                <rect
                    x="0"
                    y="0"
                    width="1"
                    height="1"
                    fill="gray"
                    opacity="0.5"
                >
                    <animate
                        attributeName="x"
                        values="0;9;0"
                        dur="2s"
                        repeatCount="indefinite"
                        calcMode="linear"
                        begin="0.1s"
                    />
                </rect>
                <rect
                    x="0"
                    y="0"
                    width="1"
                    height="1"
                    fill="gray"
                    opacity="0.25"
                >
                    <animate
                        attributeName="x"
                        values="0;9;0"
                        dur="2s"
                        repeatCount="indefinite"
                        calcMode="linear"
                        begin="0.2s"
                    />
                </rect>
                <rect
                    x="0"
                    y="0"
                    width="1"
                    height="1"
                    fill="gray"
                    opacity="0.125"
                >
                    <animate
                        attributeName="x"
                        values="0;9;0"
                        dur="2s"
                        repeatCount="indefinite"
                        calcMode="linear"
                        begin="0.3s"
                    />
                </rect>
            </svg>
            &nbsp;
        </span>
    )
}
